### ISSUE TITLE
App switcher not fully using theme coloring

### ISSUE THREAD

**Issue by OlaoluwaM** [catppuccin/gtk#177]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

The app switcher that usually pops up when you press ALT + TAB still has traces of the default gnome theme coloring

### Attach screenshots.

https://github.com/catppuccin/gtk/assets/37044906/cff7a028-0ce6-47b7-b7fd-448ce6766961

### How did you install the theme?

From source (Python script)

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

GNOME Version 46.1

**Comment by nullishamy** [comment]
The accents are not 1:1 because of colloid limitations, it's always been this way. I've got a PR open to fix this issue because I went ahead and tested it locally :+1:.

If you want to try out the test build from the PR (https://github.com/catppuccin/gtk/pull/209), you can follow the guide (https://github.com/catppuccin/gtk/blob/main/CONTRIBUTING.md#running-test-builds) :+1:
