### ISSUE TITLE
[v1.0.0-rc4] Accents are all mauve?

### ISSUE THREAD

**Issue by bobby-welch** [catppuccin/gtk#228]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

It appears that the accent colors are all mauve when using release 1.0.0-rc4.  This appears to be the same problem that was reported in  #195.  Thanks.

### How did you install the theme?

From release (install.py)

### Are you running the latest release, and if not does the issue persist there?

- [X] I am running on the latest release & the issue persists there

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

N/A

**Comment by nullishamy** [comment]
Whilst our replies #195 would indicate this was a Colloid limitation, and that it was present in 0.7.5 (before we introduced the new build system), this was not the case, and this is a regression. It should be fixed in rc5 (https://github.com/catppuccin/gtk/releases/tag/v1.0.0-rc5), so we'd appreciate if you could retest!

@bobby-welch

**Comment by bobby-welch** [comment]
v1.0.0-rc5 works!  Thank you for the quick response. =)
