### ISSUE TITLE
How to use the new themes & flags?

### ISSUE THREAD

**Issue by fufexan** [catppuccin/gtk#24]
I would like to update the Catppuccin-gtk package in Nixpkgs, but I'm not sure how to integrate the new flags from the install script.

Here are a few things I don't understand:
- There seems to be a `-c` flag for specifying light/dark variants. Is this still useful when we have separate Latte & Mocha (light & dark, respectively) themes? If yes, can you explain what these flags do in the current context?
- Is the `-n` flag used for specifying whether to install Latte or Mocha? I would like to use the `install.sh` script instead of the prebuilt theme zips, in case users want to modify the flags before installing the theme.

Maybe a few more words in the readme or some more verbose comments in the `install.sh` file would be beneficial to more packagers. I'd be glad to help with that once I understand what's going on.

Cheers

**Comment by sadrach-cl** [comment]
Hi, the install.sh and all the code is owned by Vince and his colloid theme. The code has been added as requested by his license. As for the catppuccin theme, minimal changes have been made to the colloid code so the files are generated by hand for each flavor and each color. This is for 2 reasons, to ensure the updates to the code provided by Vince in Colloid and because my time is limited to review the changes and apply them without stepping on my code and modifications. I have yet to work on a way to generate the necessary changes to the install.sh and files without interfering with the updates. That's why the readme says Work in progress. I'm sorry if I can't help you in a better way so you can work on your packages for the nix community.

**Comment by fufexan** [comment]
Thanks for the info! In the meantime I've managed to package the theme with previous flags and it worked well.

Thank you for working on the theme!
