### ISSUE TITLE
Gnome 44

### ISSUE THREAD

**Issue by MuXodious** [catppuccin/gtk#81]
Fedora 38 Beta with Gnome 44 released yesterday. I noticed that changes to quick settings in Gnome 44 kind of broke the theme as can be seen below. Thanks ^^ 

Catppuccin Mauve Frappe: 
![image](https://user-images.githubusercontent.com/64381665/225354652-475f0f35-a4f7-4887-9881-909123558a5d.png)
Default:
![image](https://user-images.githubusercontent.com/64381665/225354775-b80317b9-df93-43fa-a91a-32f59b459522.png)

**Comment by ghostx31** [comment]
We'll probably have to wait for Vince to update colloid upstream. I've been following his work currently and seems like he hasn't updated it yet.

**Comment by AyushSehrawat** [comment]
@MuXodious everything is fine except the settings i guess

![image](https://user-images.githubusercontent.com/69469790/226802862-04204b38-3053-4ba9-bb93-91116f5108b1.png)


This much is manageable for now :)

**Comment by AyushSehrawat** [comment]
@ghostx31 any updates? Or some eta 🤔

**Comment by ghostx31** [comment]
Upstream colloid does not seem to have any issues open regarding Gnome 44 and neither has Vince pushed anything related to Gnome 44 (or at least I feel so since none of their commit messages seem to suggest that). 
We'd probably have to wait for them to push some changes and I can't even test any changes unless I get Gnome 44, but Arch is still on Gnome 43 currently.

**Comment by ghostx31** [comment]
Ah alright! Thanks for the notification. I've been with university work but I'll make sure to update the repo tomorrow and create a new release.
